name: "버그 리포트"
description: "버그에 대한 제보와 기록"
labels: "bugfix"
body:
  - type: checkboxes
    id: pre-checklists
    attributes:
      label: Self Checklist
      options:
        - label: 나는 중복 이슈가 있는지 확인 했습니다.
          required: true
        - label: 나는 적절한 라벨을 설정 했습니다.
          required: true
        - label: 나는 이슈의 제목을 명령형으로 작성했습니다.
          required: true
  - type: textarea
    id: the-problem
    attributes:
      label: 문제상황
      description: 제보되거나 채널 데스크를 사용하면서 마주한 문제에 대해서 작성 해주세요. 일렉트론이나 베지어 등 외부 패키지의 문제는 해당 레포지토리에서 작성해주세요. UI상으로 문제가 드러나는 경우 스크린샷을 포함해주세요
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version of ch-desk-web
      description: "ch-desk-web 버전 -console을 열어 확인"
    validations:
      required: true
  - type: checkboxes
    id: operating-system
    attributes:
      label: OS, Environment
      description: 문제가 발생되는 환경
      options:
        - label: 환경 무관
        - label: Electron
        - label: Chrome
        - label: Safari
        - label: ETC
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 재현 과정에 대한 설명
      description: Provide steps to reproduce the problem you are experiencing.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: additional-context
    attributes:
      label: References
      description: Add any other context about the problem you are experiencing here.
