name: "버그 리포트"
description: "버그에 대한 제보와 기록"
labels: "bugfix"
body:
  - type: textarea
    id: additional-context
    attributes:
      label: References
      description: Add any other context about the problem you are experiencing here.
