name: 'Epic, Large Feature Issue Template'
description: '한번에 해결할 수 없는 크고 복잡한 이슈 혹은 피쳐의 경우 사용되는 템플릿입니다.'
labels:
  - 'epic'
body:
  - type: checkboxes
    id: pre-checklists
    attributes:
      label: Self Checklist
      options:
        - label: 나는 중복 이슈가 있는지 확인 했습니다.
          required: true
        - label: 나는 적절한 라벨을 설정 했습니다. epic에 더해 feature, refactoring, performance 등의 라벨을 추가했습니다.
          required: true
        - label: 나는 이슈의 제목을 단언형으로 작성했습니다. (ex. --- 구현, --- 리팩토링)
          required: true
        - label: 나는 해당 이슈를 관리하기 위해 마일스톤을 생성했습니다.
          required: true
  - type: textarea
    id: Summary
    attributes:
      label: 개요
      description: '이슈에 대한 요약을 작성해주세요. 목적과 목표를 작성하는 것이 권장됩니다.'
    validations:
      required: true
  - type: textarea
    id: approach
    attributes:
      label: '구현까지의 어프로치, 혹은 설계 방향을 고려하고 있는 게 있다면 작성해주세요'
      description: '지금 없더라도 추가해 나가는 것이 권장됩니다.'
  - type: textarea
    id: milestone
    attributes:
      label: '세부 태스크'
      description: '지금 없더라도 추가해 나가는 것이 권장됩니다.'
      value: |
        ```[tasklist]
          - [ ] 작성하기
        ```
  - type: textarea
    id: additional-context
    attributes:
      label: 'References'
      description: '연관 링크 추가, 그룹, 노션, 피그마 등'
    validations:
      required: true
